#!/bin/bash
#
# ssh-reverse-tunnel-indicator - Desktop status indicator ("tray icon") launcher
#
#    Copyright (C) 2020 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>

# python 2 as fallback
python=python

# but prefer python 3
if type python3 >/dev/null 2>&1; then
	python=python3
fi

"$python" -- "$(dirname "$(readlink -f "$0")")"/indicator.py
